export const theme = {
    widthCon: '90%',
    marginContent: '15px',
    marginBox: '30px',
    bgColor: 'black',
    bgArt: '#fff7e3',
    fontColor: 'white',
    flexCon: 'display: flex; flex-direction: column; align-items: center;',
    padding: '15px 0',
    fontSize: {
      s: '1.5rem',
      m: '1.75rem',
      l: '2rem',
      xl: '3rem',
      xxl: '4rem',
    },
    device: {
      mobileS: '(min-width: 320px)',
      mobileM: '(min-width: 640px)',
      tablet: '(min-width: 768px)',
      laptop: '(min-width: 1024px)',
      laptopL: '(min-width: 1280px)',
      desktop: '(min-width: 1600px)',
    },
  };