export const theme = {
    widthCon: '90%',
    marginContent: '15px',
    marginBox: '30px',
    bColor: '#003783',
    gColor: '#f8bf2c',
    fontColor: 'white',
    flexCon: 'display: flex; flex-direction: column; align-items: center;',
    padding: '15px 0',
    fontSize: {
      xs: '1.2rem',
      s: '1.5rem',
      m: '1.75rem',
      l: '2rem',
      xl: '3rem',
      xxl: '4rem',
      xxxl: '5rem',
    },
    devicePort: {
      mobileS: '@media (min-width: 360px) and (orientation: portrait)',
      mobileM: '@media (min-width: 640px) and (orientation: portrait)',
      tablet: '@media(min-width: 768px) and (orientation: portrait)',
      laptop: '@media (min-width: 1024px) and (orientation: portrait)',
      laptopL: '@media (min-width: 1280px) and (orientation: portrait)',
      desktop: '@media (min-width: 1600px) and (orientation: portrait)',
    },
    deviceLand: {
      mobileM: '@media (min-width: 640px) and (orientation: landscape)',
      tablet: '@media(min-width: 768px) and (orientation: landscape)',
      laptop: '@media (min-width: 1024px) and (orientation: landscape)',
      laptopL: '@media (min-width: 1280px) and (orientation: landscape)',
      desktop: '@media (min-width: 1600px) and (orientation: landscape)',
    },
  };